/* Auto-generated by hfs_pipeline rule selection: 24 rules total (9+3+3+9) */

/* ra: 9 rules */
uint16_t w_ra[10]; uint8_t zc_ra[10];
/* AG1: v1 is L -> 25 */
w_ra[1] = mu_L(v1);  zc_ra[1] = 25;
/* AG3: v3 is L -> 0 */
w_ra[2] = mu_L(v3);  zc_ra[2] = 0;
/* AG5: v4 is L -> 25 */
w_ra[3] = mu_L(v4);  zc_ra[3] = 25;
/* AG9: v1 is L AND v3 is H -> 75 */
w_ra[4] = min2(mu_L(v1), mu_H(v3));  zc_ra[4] = 75;
/* AG17: v1 is H AND v4 is H -> 100 */
w_ra[5] = min2(mu_H(v1), mu_H(v4));  zc_ra[5] = 100;
/* AG23: v1 is L AND v3 is H AND v4 is L -> 75 */
w_ra[6] = min2(min2(mu_L(v1), mu_H(v3)), mu_L(v4));  zc_ra[6] = 75;
/* AG28: v1 is H AND v3 is H AND v4 is M -> 75 */
w_ra[7] = min2(min2(mu_H(v1), mu_H(v3)), mu_M(v4));  zc_ra[7] = 75;
/* A1: v1 is H -> 100 */
w_ra[8] = mu_H(v1);  zc_ra[8] = 100;
/* A2: v3 is H -> 75 */
w_ra[9] = mu_H(v3);  zc_ra[9] = 75;
uint32_t num_ra = 0, den_ra = 1;
for(r = 1; r <= 9; r++) { num_ra += (uint32_t)w_ra[r] * zc_ra[r]; den_ra += w_ra[r]; }
uint8_t ra = (uint8_t)(num_ra / den_ra);

/* si: 3 rules */
uint16_t w_si[4]; uint8_t zc_si[4];
/* BG2: v2 is M -> 100 */
w_si[1] = mu_M(v2);  zc_si[1] = 100;
/* BG7: v2 is M AND v5 is L -> 100 */
w_si[2] = min2(mu_M(v2), mu_L(v5));  zc_si[2] = 100;
/* B3: v2 is H -> 50 */
w_si[3] = mu_H(v2);  zc_si[3] = 50;
uint32_t num_si = 0, den_si = 1;
for(r = 1; r <= 3; r++) { num_si += (uint32_t)w_si[r] * zc_si[r]; den_si += w_si[r]; }
uint8_t si = (uint8_t)(num_si / den_si);

/* cx: 3 rules */
uint16_t w_cx[4]; uint8_t zc_cx[4];
/* CG3: v6 is H -> 25 */
w_cx[1] = mu_H(v6);  zc_cx[1] = 25;
/* C4: v6 is M AND v7 is L -> 25 */
w_cx[2] = min2(mu_M(v6), mu_L(v7));  zc_cx[2] = 25;
/* C5: v6 is L AND v7 is L -> 50 */
w_cx[3] = min2(mu_L(v6), mu_L(v7));  zc_cx[3] = 50;
uint32_t num_cx = 0, den_cx = 1;
for(r = 1; r <= 3; r++) { num_cx += (uint32_t)w_cx[r] * zc_cx[r]; den_cx += w_cx[r]; }
uint8_t cx = (uint8_t)(num_cx / den_cx);

/* ac: 9 rules */
uint16_t w_ac[10]; uint8_t zc_ac[10];
/* TG2: ra is M -> 75 */
w_ac[1] = mu_M(ra);  zc_ac[1] = 75;
/* TG3: ra is H -> 75 */
w_ac[2] = mu_H(ra);  zc_ac[2] = 75;
/* TG14: ra is M AND cx is M -> 75 */
w_ac[3] = min2(mu_M(ra), mu_M(cx));  zc_ac[3] = 75;
/* TG16: si is L AND cx is L -> 0 */
w_ac[4] = min2(mu_L(si), mu_L(cx));  zc_ac[4] = 0;
/* TG22: ra is M AND si is M AND cx is L -> 100 */
w_ac[5] = min2(min2(mu_M(ra), mu_M(si)), mu_L(cx));  zc_ac[5] = 100;
/* TG24: ra is H AND si is L AND cx is M -> 75 */
w_ac[6] = min2(min2(mu_H(ra), mu_L(si)), mu_M(cx));  zc_ac[6] = 75;
/* T2: ra is H AND cx is M -> 100 */
w_ac[7] = min2(mu_H(ra), mu_M(cx));  zc_ac[7] = 100;
/* T3: ra is H AND cx is L -> 50 */
w_ac[8] = min2(mu_H(ra), mu_L(cx));  zc_ac[8] = 50;
/* T5: ra is M AND si is H -> 75 */
w_ac[9] = min2(mu_M(ra), mu_H(si));  zc_ac[9] = 75;
uint32_t num_ac = 0, den_ac = 1;
for(r = 1; r <= 9; r++) { num_ac += (uint32_t)w_ac[r] * zc_ac[r]; den_ac += w_ac[r]; }
uint8_t ac = (uint8_t)(num_ac / den_ac);

return ac;  /* AC in 0..100 */
