/* Auto-generated by rule_selection pipeline: 23 rules */
uint16_t w[24]; uint8_t zc[24];

/* G12(enum): v5 is L AND v6 is M -> 25 */
w[1] = min2(mu_L(v5), mu_M(v6));  zc[1] = 25;
/* G97(enum): v3 is H AND v6 is M -> 75 */
w[2] = min2(mu_H(v3), mu_M(v6));  zc[2] = 75;
/* G124(enum): v3 is H AND v4 is L AND v5 is L AND v6 is M -> 75 */
w[3] = min2(min2(min2(mu_H(v3), mu_L(v4)), mu_L(v5)), mu_M(v6));  zc[3] = 75;
/* G212(enum): v2 is M -> 100 */
w[4] = mu_M(v2);  zc[4] = 100;
/* G224(enum): v2 is M AND v5 is L AND v6 is M -> 100 */
w[5] = min2(min2(mu_M(v2), mu_L(v5)), mu_M(v6));  zc[5] = 100;
/* G229(enum): v2 is M AND v4 is L AND v7 is L -> 100 */
w[6] = min2(min2(mu_M(v2), mu_L(v4)), mu_L(v7));  zc[6] = 100;
/* G250(enum): v2 is M AND v4 is H AND v5 is L AND v7 is L -> 100 */
w[7] = min2(min2(min2(mu_M(v2), mu_H(v4)), mu_L(v5)), mu_L(v7));  zc[7] = 100;
/* G252(enum): v2 is M AND v3 is H -> 100 */
w[8] = min2(mu_M(v2), mu_H(v3));  zc[8] = 100;
/* G289(enum): v2 is H AND v5 is L AND v6 is L AND v7 is L -> 100 */
w[9] = min2(min2(min2(mu_H(v2), mu_L(v5)), mu_L(v6)), mu_L(v7));  zc[9] = 100;
/* G298(enum): v2 is H AND v4 is L AND v6 is M -> 75 */
w[10] = min2(min2(mu_H(v2), mu_L(v4)), mu_M(v6));  zc[10] = 75;
/* G301(enum): v2 is H AND v4 is L AND v6 is H AND v7 is L -> 100 */
w[11] = min2(min2(min2(mu_H(v2), mu_L(v4)), mu_H(v6)), mu_L(v7));  zc[11] = 100;
/* G316(enum): v2 is H AND v4 is M AND v5 is L AND v6 is M -> 75 */
w[12] = min2(min2(min2(mu_H(v2), mu_M(v4)), mu_L(v5)), mu_M(v6));  zc[12] = 75;
/* G336(enum): v2 is H AND v3 is H AND v5 is L AND v7 is L -> 75 */
w[13] = min2(min2(min2(mu_H(v2), mu_H(v3)), mu_L(v5)), mu_L(v7));  zc[13] = 75;
/* G337(enum): v2 is H AND v3 is H AND v5 is L AND v6 is L -> 100 */
w[14] = min2(min2(min2(mu_H(v2), mu_H(v3)), mu_L(v5)), mu_L(v6));  zc[14] = 100;
/* G341(enum): v2 is H AND v3 is H AND v4 is L AND v7 is L -> 100 */
w[15] = min2(min2(min2(mu_H(v2), mu_H(v3)), mu_L(v4)), mu_L(v7));  zc[15] = 100;
/* G348(enum): v2 is H AND v3 is H AND v4 is M AND v6 is L -> 100 */
w[16] = min2(min2(min2(mu_H(v2), mu_H(v3)), mu_M(v4)), mu_L(v6));  zc[16] = 100;
/* G372(enum): v1 is L AND v5 is M -> 100 */
w[17] = min2(mu_L(v1), mu_M(v5));  zc[17] = 100;
/* G509(enum): v1 is L AND v2 is H AND v7 is L -> 100 */
w[18] = min2(min2(mu_L(v1), mu_H(v2)), mu_L(v7));  zc[18] = 100;
/* G519(enum): v1 is L AND v2 is H AND v5 is L AND v6 is M -> 100 */
w[19] = min2(min2(min2(mu_L(v1), mu_H(v2)), mu_L(v5)), mu_M(v6));  zc[19] = 100;
/* G564(enum): v1 is H AND v4 is L AND v6 is M AND v7 is L -> 75 */
w[20] = min2(min2(min2(mu_H(v1), mu_L(v4)), mu_M(v6)), mu_L(v7));  zc[20] = 75;
/* G577(enum): v1 is H AND v4 is H AND v7 is L -> 100 */
w[21] = min2(min2(mu_H(v1), mu_H(v4)), mu_L(v7));  zc[21] = 100;
/* G678(enum): v1 is H AND v2 is H AND v4 is H AND v7 is L -> 100 */
w[22] = min2(min2(min2(mu_H(v1), mu_H(v2)), mu_H(v4)), mu_L(v7));  zc[22] = 100;
/* R6: v3 is H AND v6 is L -> 75 */
w[23] = min2(mu_H(v3), mu_L(v6));  zc[23] = 75;

uint32_t num = 0, den = 1; /* eps = 1 */
for(r = 1; r <= 23; r++) {
  num += (uint32_t)w[r] * zc[r];
  den += w[r];
}
return (uint8_t)(num / den);  /* AC in 0..100 */
