/* Auto-generated by hfs_pipeline rule selection: 19 rules total (5+4+2+8) */

/* ra: 5 rules */
uint16_t w_ra[6]; uint8_t zc_ra[6];
/* AG1: v1 is L -> 25 */
w_ra[1] = mu_L(v1);  zc_ra[1] = 25;
/* AG3: v3 is L -> 0 */
w_ra[2] = mu_L(v3);  zc_ra[2] = 0;
/* AG6: v4 is M -> 75 */
w_ra[3] = mu_M(v4);  zc_ra[3] = 75;
/* AG19: v3 is H AND v4 is L -> 75 */
w_ra[4] = min2(mu_H(v3), mu_L(v4));  zc_ra[4] = 75;
/* A2: v3 is H -> 75 */
w_ra[5] = mu_H(v3);  zc_ra[5] = 75;
uint32_t num_ra = 0, den_ra = 1;
for(r = 1; r <= 5; r++) { num_ra += (uint32_t)w_ra[r] * zc_ra[r]; den_ra += w_ra[r]; }
uint8_t ra = (uint8_t)(num_ra / den_ra);

/* si: 4 rules */
uint16_t w_si[5]; uint8_t zc_si[5];
/* BG4: v5 is L -> 25 */
w_si[1] = mu_L(v5);  zc_si[1] = 25;
/* BG6: v2 is M AND v5 is L -> 100 */
w_si[2] = min2(mu_M(v2), mu_L(v5));  zc_si[2] = 100;
/* B2: v5 is H -> 75 */
w_si[3] = mu_H(v5);  zc_si[3] = 75;
/* B3: v2 is H -> 50 */
w_si[4] = mu_H(v2);  zc_si[4] = 50;
uint32_t num_si = 0, den_si = 1;
for(r = 1; r <= 4; r++) { num_si += (uint32_t)w_si[r] * zc_si[r]; den_si += w_si[r]; }
uint8_t si = (uint8_t)(num_si / den_si);

/* cx: 2 rules */
uint16_t w_cx[3]; uint8_t zc_cx[3];
/* CG2: v6 is M -> 25 */
w_cx[1] = mu_M(v6);  zc_cx[1] = 25;
/* C5: v6 is L AND v7 is L -> 50 */
w_cx[2] = min2(mu_L(v6), mu_L(v7));  zc_cx[2] = 50;
uint32_t num_cx = 0, den_cx = 1;
for(r = 1; r <= 2; r++) { num_cx += (uint32_t)w_cx[r] * zc_cx[r]; den_cx += w_cx[r]; }
uint8_t cx = (uint8_t)(num_cx / den_cx);

/* ac: 8 rules */
uint16_t w_ac[9]; uint8_t zc_ac[9];
/* TG9: ra is M AND si is M -> 100 */
w_ac[1] = min2(mu_M(ra), mu_M(si));  zc_ac[1] = 100;
/* TG10: ra is H AND si is M -> 75 */
w_ac[2] = min2(mu_H(ra), mu_M(si));  zc_ac[2] = 75;
/* TG15: si is L AND cx is L -> 0 */
w_ac[3] = min2(mu_L(si), mu_L(cx));  zc_ac[3] = 0;
/* TG21: ra is M AND si is M AND cx is L -> 100 */
w_ac[4] = min2(min2(mu_M(ra), mu_M(si)), mu_L(cx));  zc_ac[4] = 100;
/* T2: ra is H AND cx is M -> 100 */
w_ac[5] = min2(mu_H(ra), mu_M(cx));  zc_ac[5] = 100;
/* T4: si is H AND cx is M -> 75 */
w_ac[6] = min2(mu_H(si), mu_M(cx));  zc_ac[6] = 75;
/* T7: ra is L AND si is L AND cx is L -> 0 */
w_ac[7] = min2(min2(mu_L(ra), mu_L(si)), mu_L(cx));  zc_ac[7] = 0;
/* T8: ra is L AND si is L AND cx is M -> 0 */
w_ac[8] = min2(min2(mu_L(ra), mu_L(si)), mu_M(cx));  zc_ac[8] = 0;
uint32_t num_ac = 0, den_ac = 1;
for(r = 1; r <= 8; r++) { num_ac += (uint32_t)w_ac[r] * zc_ac[r]; den_ac += w_ac[r]; }
uint8_t ac = (uint8_t)(num_ac / den_ac);

return ac;  /* AC in 0..100 */
