/* Auto-generated by rule_selection pipeline: 16 rules */
uint16_t w[17]; uint8_t zc[17];

/* G31(enum): v5 is H -> 100 */
w[1] = mu_H(v5);  zc[1] = 100;
/* G99(enum): v4 is H AND v5 is L AND v7 is L -> 100 */
w[2] = min2(min2(mu_H(v4), mu_L(v5)), mu_L(v7));  zc[2] = 100;
/* G130(enum): v3 is L AND v5 is L AND v6 is H -> 0 */
w[3] = min2(min2(mu_L(v3), mu_L(v5)), mu_H(v6));  zc[3] = 0;
/* G198(enum): v3 is L AND v4 is H AND v5 is L -> 100 */
w[4] = min2(min2(mu_L(v3), mu_H(v4)), mu_L(v5));  zc[4] = 100;
/* G271(enum): v2 is L AND v7 is M -> 25 */
w[5] = min2(mu_L(v2), mu_M(v7));  zc[5] = 25;
/* G703(enum): v1 is L AND v3 is L AND v5 is L AND v7 is H -> 100 */
w[6] = min2(min2(min2(mu_L(v1), mu_L(v3)), mu_L(v5)), mu_H(v7));  zc[6] = 100;
/* G760(enum): v1 is L AND v3 is H AND v7 is L -> 100 */
w[7] = min2(min2(mu_L(v1), mu_H(v3)), mu_L(v7));  zc[7] = 100;
/* G829(enum): v1 is L AND v2 is L AND v3 is L AND v7 is L -> 0 */
w[8] = min2(min2(min2(mu_L(v1), mu_L(v2)), mu_L(v3)), mu_L(v7));  zc[8] = 0;
/* G858(wm): v1 is L AND v2 is L AND v3 is M AND v4 is L AND v5 is L AND v6 is L AND v7 is L -> 0 */
w[9] = min2(min2(min2(min2(min2(min2(mu_L(v1), mu_L(v2)), mu_M(v3)), mu_L(v4)), mu_L(v5)), mu_L(v6)), mu_L(v7));  zc[9] = 0;
/* G899(enum): v1 is L AND v2 is M AND v3 is M AND v6 is M -> 25 */
w[10] = min2(min2(min2(mu_L(v1), mu_M(v2)), mu_M(v3)), mu_M(v6));  zc[10] = 25;
/* G945(wm): v1 is L AND v2 is H AND v3 is L AND v4 is L AND v5 is H AND v6 is L AND v7 is L -> 100 */
w[11] = min2(min2(min2(min2(min2(min2(mu_L(v1), mu_H(v2)), mu_L(v3)), mu_L(v4)), mu_H(v5)), mu_L(v6)), mu_L(v7));  zc[11] = 100;
/* G985(enum): v1 is M AND v4 is L AND v6 is M -> 0 */
w[12] = min2(min2(mu_M(v1), mu_L(v4)), mu_M(v6));  zc[12] = 0;
/* R1: v1 is H -> 100 */
w[13] = mu_H(v1);  zc[13] = 100;
/* R2: v7 is H -> 100 */
w[14] = mu_H(v7);  zc[14] = 100;
/* R6: v3 is H AND v6 is L -> 75 */
w[15] = min2(mu_H(v3), mu_L(v6));  zc[15] = 75;
/* R9: v5 is H AND v6 is L -> 75 */
w[16] = min2(mu_H(v5), mu_L(v6));  zc[16] = 75;

uint32_t num = 0, den = 1; /* eps = 1 */
for(r = 1; r <= 16; r++) {
  num += (uint32_t)w[r] * zc[r];
  den += w[r];
}
return (uint8_t)(num / den);  /* AC in 0..100 */
