/* Auto-generated by rule_selection pipeline: 15 rules */
uint16_t w[16]; uint8_t zc[16];

/* G12(enum): v5 is L AND v6 is M -> 25 */
w[1] = min2(mu_L(v5), mu_M(v6));  zc[1] = 25;
/* G14(enum): v5 is L AND v6 is H -> 25 */
w[2] = min2(mu_L(v5), mu_H(v6));  zc[2] = 25;
/* G56(enum): v4 is H -> 100 */
w[3] = mu_H(v4);  zc[3] = 100;
/* G98(enum): v3 is H AND v7 is L -> 75 */
w[4] = min2(mu_H(v3), mu_L(v7));  zc[4] = 75;
/* G117(enum): v3 is H AND v4 is L -> 75 */
w[5] = min2(mu_H(v3), mu_L(v4));  zc[5] = 75;
/* G121(enum): v3 is H AND v4 is L AND v6 is M -> 75 */
w[6] = min2(min2(mu_H(v3), mu_L(v4)), mu_M(v6));  zc[6] = 75;
/* G149(enum): v3 is H AND v4 is H AND v5 is L -> 100 */
w[7] = min2(min2(mu_H(v3), mu_H(v4)), mu_L(v5));  zc[7] = 100;
/* G206(enum): v2 is L AND v3 is H AND v6 is M -> 25 */
w[8] = min2(min2(mu_L(v2), mu_H(v3)), mu_M(v6));  zc[8] = 25;
/* G218(enum): v2 is M AND v7 is L -> 100 */
w[9] = min2(mu_M(v2), mu_L(v7));  zc[9] = 100;
/* G321(enum): v2 is H AND v4 is M AND v5 is L -> 75 */
w[10] = min2(min2(mu_H(v2), mu_M(v4)), mu_L(v5));  zc[10] = 75;
/* G345(enum): v2 is H AND v3 is H AND v5 is L AND v6 is L -> 100 */
w[11] = min2(min2(min2(mu_H(v2), mu_H(v3)), mu_L(v5)), mu_L(v6));  zc[11] = 100;
/* G355(enum): v2 is H AND v3 is H AND v4 is M AND v7 is L -> 75 */
w[12] = min2(min2(min2(mu_H(v2), mu_H(v3)), mu_M(v4)), mu_L(v7));  zc[12] = 75;
/* G495(enum): v1 is L AND v2 is L AND v3 is H AND v6 is M -> 25 */
w[13] = min2(min2(min2(mu_L(v1), mu_L(v2)), mu_H(v3)), mu_M(v6));  zc[13] = 25;
/* G501(enum): v1 is L AND v2 is M -> 100 */
w[14] = min2(mu_L(v1), mu_M(v2));  zc[14] = 100;
/* G548(enum): v1 is L AND v2 is H AND v3 is H -> 100 */
w[15] = min2(min2(mu_L(v1), mu_H(v2)), mu_H(v3));  zc[15] = 100;

uint32_t num = 0, den = 1; /* eps = 1 */
for(r = 1; r <= 15; r++) {
  num += (uint32_t)w[r] * zc[r];
  den += w[r];
}
return (uint8_t)(num / den);  /* AC in 0..100 */
