/* Auto-generated by rule_selection pipeline: 19 rules */
uint16_t w[20]; uint8_t zc[20];

/* G5(enum): v6 is M AND v7 is L -> 25 */
w[1] = min2(mu_M(v6), mu_L(v7));  zc[1] = 25;
/* G106(enum): v3 is H AND v4 is L AND v7 is L -> 75 */
w[2] = min2(min2(mu_H(v3), mu_L(v4)), mu_L(v7));  zc[2] = 75;
/* G108(enum): v3 is H AND v4 is L AND v6 is L AND v7 is L -> 100 */
w[3] = min2(min2(min2(mu_H(v3), mu_L(v4)), mu_L(v6)), mu_L(v7));  zc[3] = 100;
/* G121(enum): v3 is H AND v4 is M AND v6 is L AND v7 is L -> 100 */
w[4] = min2(min2(min2(mu_H(v3), mu_M(v4)), mu_L(v6)), mu_L(v7));  zc[4] = 100;
/* G131(enum): v3 is H AND v4 is H -> 100 */
w[5] = min2(mu_H(v3), mu_H(v4));  zc[5] = 100;
/* G138(enum): v3 is H AND v4 is H AND v5 is L AND v7 is L -> 100 */
w[6] = min2(min2(min2(mu_H(v3), mu_H(v4)), mu_L(v5)), mu_L(v7));  zc[6] = 100;
/* G193(enum): v2 is L AND v3 is H AND v5 is L -> 25 */
w[7] = min2(min2(mu_L(v2), mu_H(v3)), mu_L(v5));  zc[7] = 25;
/* G200(enum): v2 is M AND v7 is L -> 100 */
w[8] = min2(mu_M(v2), mu_L(v7));  zc[8] = 100;
/* G209(enum): v2 is M AND v5 is L AND v6 is M -> 100 */
w[9] = min2(min2(mu_M(v2), mu_L(v5)), mu_M(v6));  zc[9] = 100;
/* G272(enum): v2 is H AND v4 is M -> 75 */
w[10] = min2(mu_H(v2), mu_M(v4));  zc[10] = 75;
/* G353(enum): v1 is L AND v4 is M AND v6 is M AND v7 is L -> 75 */
w[11] = min2(min2(min2(mu_L(v1), mu_M(v4)), mu_M(v6)), mu_L(v7));  zc[11] = 75;
/* G456(enum): v1 is L AND v2 is M AND v5 is L AND v7 is L -> 100 */
w[12] = min2(min2(min2(mu_L(v1), mu_M(v2)), mu_L(v5)), mu_L(v7));  zc[12] = 100;
/* G477(enum): v1 is L AND v2 is H AND v5 is L AND v7 is L -> 100 */
w[13] = min2(min2(min2(mu_L(v1), mu_H(v2)), mu_L(v5)), mu_L(v7));  zc[13] = 100;
/* G499(enum): v1 is L AND v2 is H AND v3 is H AND v5 is L -> 100 */
w[14] = min2(min2(min2(mu_L(v1), mu_H(v2)), mu_H(v3)), mu_L(v5));  zc[14] = 100;
/* G510(enum): v1 is H AND v6 is L AND v7 is L -> 100 */
w[15] = min2(min2(mu_H(v1), mu_L(v6)), mu_L(v7));  zc[15] = 100;
/* G523(enum): v1 is H AND v4 is L AND v6 is M -> 75 */
w[16] = min2(min2(mu_H(v1), mu_L(v4)), mu_M(v6));  zc[16] = 75;
/* G556(enum): v1 is H AND v3 is H AND v6 is L -> 100 */
w[17] = min2(min2(mu_H(v1), mu_H(v3)), mu_L(v6));  zc[17] = 100;
/* G607(enum): v1 is H AND v2 is M AND v5 is L AND v7 is L -> 100 */
w[18] = min2(min2(min2(mu_H(v1), mu_M(v2)), mu_L(v5)), mu_L(v7));  zc[18] = 100;
/* G653(wm): v1 is H AND v2 is H AND v3 is H AND v4 is L AND v5 is L AND v6 is M AND v7 is L -> 75 */
w[19] = min2(min2(min2(min2(min2(min2(mu_H(v1), mu_H(v2)), mu_H(v3)), mu_L(v4)), mu_L(v5)), mu_M(v6)), mu_L(v7));  zc[19] = 75;

uint32_t num = 0, den = 1; /* eps = 1 */
for(r = 1; r <= 19; r++) {
  num += (uint32_t)w[r] * zc[r];
  den += w[r];
}
return (uint8_t)(num / den);  /* AC in 0..100 */
