/* Auto-generated by hfs_pipeline rule selection: 12 rules total (3+4+2+3) */

/* ra: 3 rules */
uint16_t w_ra[4]; uint8_t zc_ra[4];
/* AG9: v1 is L AND v3 is H -> 75 */
w_ra[1] = min2(mu_L(v1), mu_H(v3));  zc_ra[1] = 75;
/* AG12: v1 is L AND v4 is L -> 0 */
w_ra[2] = min2(mu_L(v1), mu_L(v4));  zc_ra[2] = 0;
/* A1: v1 is H -> 100 */
w_ra[3] = mu_H(v1);  zc_ra[3] = 100;
uint32_t num_ra = 0, den_ra = 1;
for(r = 1; r <= 3; r++) { num_ra += (uint32_t)w_ra[r] * zc_ra[r]; den_ra += w_ra[r]; }
uint8_t ra = (uint8_t)(num_ra / den_ra);

/* si: 4 rules */
uint16_t w_si[5]; uint8_t zc_si[5];
/* BG4: v5 is L -> 25 */
w_si[1] = mu_L(v5);  zc_si[1] = 25;
/* BG6: v2 is M AND v5 is L -> 100 */
w_si[2] = min2(mu_M(v2), mu_L(v5));  zc_si[2] = 100;
/* B4: v2 is M AND v5 is M -> 50 */
w_si[3] = min2(mu_M(v2), mu_M(v5));  zc_si[3] = 50;
/* B5: v2 is L AND v5 is L -> 0 */
w_si[4] = min2(mu_L(v2), mu_L(v5));  zc_si[4] = 0;
uint32_t num_si = 0, den_si = 1;
for(r = 1; r <= 4; r++) { num_si += (uint32_t)w_si[r] * zc_si[r]; den_si += w_si[r]; }
uint8_t si = (uint8_t)(num_si / den_si);

/* cx: 2 rules */
uint16_t w_cx[3]; uint8_t zc_cx[3];
/* CG2: v6 is M -> 25 */
w_cx[1] = mu_M(v6);  zc_cx[1] = 25;
/* C5: v6 is L AND v7 is L -> 50 */
w_cx[2] = min2(mu_L(v6), mu_L(v7));  zc_cx[2] = 50;
uint32_t num_cx = 0, den_cx = 1;
for(r = 1; r <= 2; r++) { num_cx += (uint32_t)w_cx[r] * zc_cx[r]; den_cx += w_cx[r]; }
uint8_t cx = (uint8_t)(num_cx / den_cx);

/* ac: 3 rules */
uint16_t w_ac[4]; uint8_t zc_ac[4];
/* TG4: si is M -> 100 */
w_ac[1] = mu_M(si);  zc_ac[1] = 100;
/* TG18: si is M AND cx is M -> 100 */
w_ac[2] = min2(mu_M(si), mu_M(cx));  zc_ac[2] = 100;
/* T3: ra is H AND cx is L -> 50 */
w_ac[3] = min2(mu_H(ra), mu_L(cx));  zc_ac[3] = 50;
uint32_t num_ac = 0, den_ac = 1;
for(r = 1; r <= 3; r++) { num_ac += (uint32_t)w_ac[r] * zc_ac[r]; den_ac += w_ac[r]; }
uint8_t ac = (uint8_t)(num_ac / den_ac);

return ac;  /* AC in 0..100 */
