/* Auto-generated by rule_selection pipeline: 12 rules */
uint16_t w[13]; uint8_t zc[13];

/* G12(enum): v5 is L AND v6 is M -> 25 */
w[1] = min2(mu_L(v5), mu_M(v6));  zc[1] = 25;
/* G52(enum): v4 is H -> 100 */
w[2] = mu_H(v4);  zc[2] = 100;
/* G64(enum): v3 is L -> 0 */
w[3] = mu_L(v3);  zc[3] = 0;
/* G225(enum): v2 is M AND v7 is L -> 100 */
w[4] = min2(mu_M(v2), mu_L(v7));  zc[4] = 100;
/* G226(enum): v2 is M AND v6 is L -> 100 */
w[5] = min2(mu_M(v2), mu_L(v6));  zc[5] = 100;
/* G262(enum): v2 is M AND v3 is H AND v7 is L -> 100 */
w[6] = min2(min2(mu_M(v2), mu_H(v3)), mu_L(v7));  zc[6] = 100;
/* G286(enum): v2 is H AND v7 is L -> 75 */
w[7] = min2(mu_H(v2), mu_L(v7));  zc[7] = 75;
/* G295(enum): v2 is H AND v5 is L AND v6 is L -> 100 */
w[8] = min2(min2(mu_H(v2), mu_L(v5)), mu_L(v6));  zc[8] = 100;
/* G342(enum): v2 is H AND v3 is H AND v5 is L -> 75 */
w[9] = min2(min2(mu_H(v2), mu_H(v3)), mu_L(v5));  zc[9] = 75;
/* G466(enum): v1 is L AND v2 is L AND v4 is L AND v6 is H -> 0 */
w[10] = min2(min2(min2(mu_L(v1), mu_L(v2)), mu_L(v4)), mu_H(v6));  zc[10] = 0;
/* G537(enum): v1 is L AND v2 is H AND v3 is H AND v7 is L -> 100 */
w[11] = min2(min2(min2(mu_L(v1), mu_H(v2)), mu_H(v3)), mu_L(v7));  zc[11] = 100;
/* G614(enum): v1 is H AND v3 is H AND v4 is L AND v6 is M -> 75 */
w[12] = min2(min2(min2(mu_H(v1), mu_H(v3)), mu_L(v4)), mu_M(v6));  zc[12] = 75;

uint32_t num = 0, den = 1; /* eps = 1 */
for(r = 1; r <= 12; r++) {
  num += (uint32_t)w[r] * zc[r];
  den += w[r];
}
return (uint8_t)(num / den);  /* AC in 0..100 */
