/* Auto-generated by rule_selection pipeline: 13 rules */
uint16_t w[14]; uint8_t zc[14];

/* G5(enum): v6 is M AND v7 is L -> 25 */
w[1] = min2(mu_M(v6), mu_L(v7));  zc[1] = 25;
/* G44(enum): v4 is H AND v7 is L -> 100 */
w[2] = min2(mu_H(v4), mu_L(v7));  zc[2] = 100;
/* G106(enum): v3 is H AND v4 is L AND v6 is L -> 100 */
w[3] = min2(min2(mu_H(v3), mu_L(v4)), mu_L(v6));  zc[3] = 100;
/* G112(enum): v3 is H AND v4 is L AND v5 is L AND v6 is L -> 100 */
w[4] = min2(min2(min2(mu_H(v3), mu_L(v4)), mu_L(v5)), mu_L(v6));  zc[4] = 100;
/* G183(enum): v2 is L AND v3 is H AND v6 is M AND v7 is L -> 25 */
w[5] = min2(min2(min2(mu_L(v2), mu_H(v3)), mu_M(v6)), mu_L(v7));  zc[5] = 25;
/* G204(enum): v2 is M AND v5 is L -> 100 */
w[6] = min2(mu_M(v2), mu_L(v5));  zc[6] = 100;
/* G243(enum): v2 is M AND v3 is H AND v6 is M AND v7 is L -> 100 */
w[7] = min2(min2(min2(mu_M(v2), mu_H(v3)), mu_M(v6)), mu_L(v7));  zc[7] = 100;
/* G266(enum): v2 is H -> 75 */
w[8] = mu_H(v2);  zc[8] = 75;
/* G381(enum): v1 is L AND v4 is H AND v7 is L -> 100 */
w[9] = min2(min2(mu_L(v1), mu_H(v4)), mu_L(v7));  zc[9] = 100;
/* G482(enum): v1 is L AND v2 is M -> 100 */
w[10] = min2(mu_L(v1), mu_M(v2));  zc[10] = 100;
/* G492(enum): v1 is L AND v2 is M AND v4 is L -> 100 */
w[11] = min2(min2(mu_L(v1), mu_M(v2)), mu_L(v4));  zc[11] = 100;
/* G520(enum): v1 is L AND v2 is H AND v5 is L -> 100 */
w[12] = min2(min2(mu_L(v1), mu_H(v2)), mu_L(v5));  zc[12] = 100;
/* R16: v3 is H AND v7 is H -> 100 */
w[13] = min2(mu_H(v3), mu_H(v7));  zc[13] = 100;

uint32_t num = 0, den = 1; /* eps = 1 */
for(r = 1; r <= 13; r++) {
  num += (uint32_t)w[r] * zc[r];
  den += w[r];
}
return (uint8_t)(num / den);  /* AC in 0..100 */
