"""
report.py -- Pareto front reporting, expert-base overlap, and C export
======================================================================
Outputs:
  pareto_front.csv     one row per non-dominated rule base (train + test
                       metrics, rule count, expert overlap)
  selected_rules.txt   human-readable listing of the knee-point base
  selected_rules.c     drop-in body for fuzzrid_fuzzy_infer_ac() on the
                       integer 0..100 scale (min t-norm, Sugeno weighted
                       average) so the selected base deploys unchanged
  overlap_report.txt   Jaccard/containment of every Pareto base vs R1-R18
"""

from __future__ import annotations
import numpy as np
import pandas as pd

from fuzzy import DONT_CARE, TERM_NAMES, rule_str, sugeno_ac
from optimize import f1_fpr

MU_FN = {1: "mu_L", 2: "mu_M", 3: "mu_H"}


def base_metrics(mask, W, z, y, ac_thr):
    ac = sugeno_ac(W, z, subset=mask)
    f1, fpr, cm = f1_fpr(ac, y, ac_thr)
    return f1, fpr, cm


def overlap_stats(mask: np.ndarray, expert_mask: np.ndarray):
    sel = set(np.nonzero(mask)[0])
    exp = set(np.nonzero(expert_mask)[0])
    inter = len(sel & exp)
    union = len(sel | exp)
    return dict(n_selected=len(sel), n_expert_in_base=inter,
                jaccard=inter / union if union else 0.0,
                expert_coverage=inter / len(exp) if exp else 0.0)


def pareto_table(masks, F, pool, y_tr, W_te, y_te, ac_thr, names):
    rows = []
    for i, mask in enumerate(masks):
        f1_tr, fpr_tr, _ = base_metrics(mask, pool["W"], pool["z"], y_tr, ac_thr)
        f1_te, fpr_te, cm = base_metrics(mask, W_te, pool["z"], y_te, ac_thr)
        ov = overlap_stats(mask, pool["expert_mask"])
        rows.append(dict(base_id=i, n_rules=int(mask.sum()),
                         f1_train=round(f1_tr, 4), fpr_train=round(fpr_tr, 4),
                         f1_test=round(f1_te, 4), fpr_test=round(fpr_te, 4),
                         recall_test=round(cm["recall"], 4),
                         precision_test=round(cm["precision"], 4),
                         expert_rules_included=ov["n_expert_in_base"],
                         jaccard_vs_expert=round(ov["jaccard"], 3),
                         expert_coverage=round(ov["expert_coverage"], 3),
                         rules="; ".join(names[j] for j in np.nonzero(mask)[0])))
    return pd.DataFrame(rows).sort_values(["f1_test", "n_rules"],
                                          ascending=[False, True])


def rules_listing(mask, pool):
    lines = []
    for j in np.nonzero(mask)[0]:
        tag = "[expert]" if pool["expert_mask"][j] else "[generated]"
        lines.append(f"{pool['names'][j]:>14} {tag:11} "
                     f"{rule_str(pool['antecedents'][j], pool['z'][j])}   "
                     f"(support={pool['support'][j]:.3f}, conf={pool['conf'][j]:.2f})")
    return "\n".join(lines)


def export_c(mask, pool, fname):
    """Emit the selected base as the rule block of fuzzrid_fuzzy_infer_ac().
    Weights on 0..100 integer scale to match firmware; multi-term rules use
    nested min2()."""
    idx = np.nonzero(mask)[0]
    n = len(idx)
    out = [f"/* Auto-generated by rule_selection pipeline: {n} rules */",
           f"uint16_t w[{n + 1}]; uint8_t zc[{n + 1}];", ""]
    for r, j in enumerate(idx, start=1):
        ant, z = pool["antecedents"][j], int(pool["z"][j])
        terms = [(i + 1, t) for i, t in enumerate(ant) if t != DONT_CARE]
        expr = f"{MU_FN[terms[0][1]]}(v{terms[0][0]})"
        for feat, t in terms[1:]:
            expr = f"min2({expr}, {MU_FN[t]}(v{feat}))"
        cond = " AND ".join(f"v{f} is {TERM_NAMES[t]}" for f, t in terms)
        out.append(f"/* {pool['names'][j]}: {cond} -> {z} */")
        out.append(f"w[{r}] = {expr};  zc[{r}] = {z};")
    out += ["",
            "uint32_t num = 0, den = 1; /* eps = 1 */",
            f"for(r = 1; r <= {n}; r++) {{",
            "  num += (uint32_t)w[r] * zc[r];",
            "  den += w[r];",
            "}",
            "return (uint8_t)(num / den);  /* AC in 0..100 */"]
    with open(fname, "w") as f:
        f.write("\n".join(out) + "\n")
