/* Auto-generated by rule_selection pipeline: 16 rules */
uint16_t w[17]; uint8_t zc[17];

/* G194(enum): v2 is L AND v3 is H AND v6 is M -> 25 */
w[1] = min2(min2(mu_L(v2), mu_H(v3)), mu_M(v6));  zc[1] = 25;
/* G205(enum): v2 is M -> 100 */
w[2] = mu_M(v2);  zc[2] = 100;
/* G222(enum): v2 is M AND v5 is M AND v7 is L -> 100 */
w[3] = min2(min2(mu_M(v2), mu_M(v5)), mu_L(v7));  zc[3] = 100;
/* G248(enum): v2 is M AND v4 is H AND v5 is L AND v6 is M -> 100 */
w[4] = min2(min2(min2(mu_M(v2), mu_H(v4)), mu_L(v5)), mu_M(v6));  zc[4] = 100;
/* G249(enum): v2 is M AND v3 is H -> 100 */
w[5] = min2(mu_M(v2), mu_H(v3));  zc[5] = 100;
/* G257(enum): v2 is M AND v3 is H AND v5 is L -> 100 */
w[6] = min2(min2(mu_M(v2), mu_H(v3)), mu_L(v5));  zc[6] = 100;
/* G265(enum): v2 is M AND v3 is H AND v4 is L -> 100 */
w[7] = min2(min2(mu_M(v2), mu_H(v3)), mu_L(v4));  zc[7] = 100;
/* G306(enum): v2 is H AND v4 is L AND v5 is L AND v6 is H -> 75 */
w[8] = min2(min2(min2(mu_H(v2), mu_L(v4)), mu_L(v5)), mu_H(v6));  zc[8] = 75;
/* G409(enum): v1 is L AND v3 is L AND v5 is L AND v6 is M -> 0 */
w[9] = min2(min2(min2(mu_L(v1), mu_L(v3)), mu_L(v5)), mu_M(v6));  zc[9] = 0;
/* G415(enum): v1 is L AND v3 is L AND v4 is L AND v6 is H -> 0 */
w[10] = min2(min2(min2(mu_L(v1), mu_L(v3)), mu_L(v4)), mu_H(v6));  zc[10] = 0;
/* G499(enum): v1 is L AND v2 is M AND v4 is H AND v6 is M -> 100 */
w[11] = min2(min2(min2(mu_L(v1), mu_M(v2)), mu_H(v4)), mu_M(v6));  zc[11] = 100;
/* G509(enum): v1 is L AND v2 is H -> 100 */
w[12] = min2(mu_L(v1), mu_H(v2));  zc[12] = 100;
/* G518(enum): v1 is L AND v2 is H AND v5 is L AND v6 is M -> 100 */
w[13] = min2(min2(min2(mu_L(v1), mu_H(v2)), mu_L(v5)), mu_M(v6));  zc[13] = 100;
/* G580(enum): v1 is H AND v3 is L AND v5 is L AND v6 is M -> 0 */
w[14] = min2(min2(min2(mu_H(v1), mu_L(v3)), mu_L(v5)), mu_M(v6));  zc[14] = 0;
/* R3: v4 is H AND v6 is L -> 75 */
w[15] = min2(mu_H(v4), mu_L(v6));  zc[15] = 75;
/* R6: v3 is H AND v6 is L -> 75 */
w[16] = min2(mu_H(v3), mu_L(v6));  zc[16] = 75;

uint32_t num = 0, den = 1; /* eps = 1 */
for(r = 1; r <= 16; r++) {
  num += (uint32_t)w[r] * zc[r];
  den += w[r];
}
return (uint8_t)(num / den);  /* AC in 0..100 */
