/* Auto-generated by rule_selection pipeline: 8 rules */
uint16_t w[9]; uint8_t zc[9];

/* G28(enum): v5 is H AND v7 is L -> 100 */
w[1] = min2(mu_H(v5), mu_L(v7));  zc[1] = 100;
/* G216(enum): v3 is H -> 100 */
w[2] = mu_H(v3);  zc[2] = 100;
/* G686(enum): v1 is L AND v2 is L AND v7 is H -> 100 */
w[3] = min2(min2(mu_L(v1), mu_L(v2)), mu_H(v7));  zc[3] = 100;
/* G727(enum): v1 is L AND v2 is L AND v3 is L AND v7 is L -> 0 */
w[4] = min2(min2(min2(mu_L(v1), mu_L(v2)), mu_L(v3)), mu_L(v7));  zc[4] = 0;
/* G728(enum): v1 is L AND v2 is L AND v3 is L AND v7 is M -> 0 */
w[5] = min2(min2(min2(mu_L(v1), mu_L(v2)), mu_L(v3)), mu_M(v7));  zc[5] = 0;
/* G752(enum): v1 is L AND v2 is L AND v3 is M AND v5 is L -> 0 */
w[6] = min2(min2(min2(mu_L(v1), mu_L(v2)), mu_M(v3)), mu_L(v5));  zc[6] = 0;
/* G873(enum): v1 is M AND v3 is L AND v4 is L -> 25 */
w[7] = min2(min2(mu_M(v1), mu_L(v3)), mu_L(v4));  zc[7] = 25;
/* R1: v1 is H -> 100 */
w[8] = mu_H(v1);  zc[8] = 100;

uint32_t num = 0, den = 1; /* eps = 1 */
for(r = 1; r <= 8; r++) {
  num += (uint32_t)w[r] * zc[r];
  den += w[r];
}
return (uint8_t)(num / den);  /* AC in 0..100 */
