/* Auto-generated by rule_selection pipeline: 12 rules */
uint16_t w[13]; uint8_t zc[13];

/* G113(enum): v3 is H AND v4 is L AND v6 is L -> 100 */
w[1] = min2(min2(mu_H(v3), mu_L(v4)), mu_L(v6));  zc[1] = 100;
/* G204(enum): v2 is L AND v3 is H AND v6 is M -> 25 */
w[2] = min2(min2(mu_L(v2), mu_H(v3)), mu_M(v6));  zc[2] = 25;
/* G213(enum): v2 is L AND v3 is H AND v4 is L AND v6 is M -> 25 */
w[3] = min2(min2(min2(mu_L(v2), mu_H(v3)), mu_L(v4)), mu_M(v6));  zc[3] = 25;
/* G225(enum): v2 is M AND v5 is L -> 100 */
w[4] = min2(mu_M(v2), mu_L(v5));  zc[4] = 100;
/* G266(enum): v2 is M AND v3 is H AND v5 is L AND v7 is L -> 100 */
w[5] = min2(min2(min2(mu_M(v2), mu_H(v3)), mu_L(v5)), mu_L(v7));  zc[5] = 100;
/* G273(enum): v2 is M AND v3 is H AND v4 is L AND v7 is L -> 100 */
w[6] = min2(min2(min2(mu_M(v2), mu_H(v3)), mu_L(v4)), mu_L(v7));  zc[6] = 100;
/* G277(enum): v2 is M AND v3 is H AND v4 is M -> 100 */
w[7] = min2(min2(mu_M(v2), mu_H(v3)), mu_M(v4));  zc[7] = 100;
/* G337(enum): v2 is H AND v3 is H AND v6 is L AND v7 is L -> 100 */
w[8] = min2(min2(min2(mu_H(v2), mu_H(v3)), mu_L(v6)), mu_L(v7));  zc[8] = 100;
/* G380(enum): v1 is L AND v5 is M AND v7 is L -> 100 */
w[9] = min2(min2(mu_L(v1), mu_M(v5)), mu_L(v7));  zc[9] = 100;
/* G520(enum): v1 is L AND v2 is M AND v4 is H -> 100 */
w[10] = min2(min2(mu_L(v1), mu_M(v2)), mu_H(v4));  zc[10] = 100;
/* G540(enum): v1 is L AND v2 is H AND v5 is L AND v7 is L -> 100 */
w[11] = min2(min2(min2(mu_L(v1), mu_H(v2)), mu_L(v5)), mu_L(v7));  zc[11] = 100;
/* G581(enum): v1 is H AND v4 is L AND v6 is H AND v7 is L -> 25 */
w[12] = min2(min2(min2(mu_H(v1), mu_L(v4)), mu_H(v6)), mu_L(v7));  zc[12] = 25;

uint32_t num = 0, den = 1; /* eps = 1 */
for(r = 1; r <= 12; r++) {
  num += (uint32_t)w[r] * zc[r];
  den += w[r];
}
return (uint8_t)(num / den);  /* AC in 0..100 */
